In [1]:
from ultimatetictactoe import ultimatetictactoe
from algo.base_algo.base_algo import RandomAgent, NeuralAgent, ManualAgent

import torch
from torch import nn
import torch.optim as optim

import numpy as np

import random

c:\Users\andre\OneDrive\Desktop\UNI\magistrale\Reinforcement\multi_agent\env\Lib\site-packages\pygame\pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [2]:
env = ultimatetictactoe.env(render_mode="human")
env.reset(42)

In [3]:
env.last()

({'observation': array([[[0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0]],
  
         [[0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0],
          [0, 0, 0, 0, 0, 0, 0, 0, 0]]], dtype=int8),
  'action_mask': array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 

In [4]:
env.agents

['player_1', 'player_2']

In [5]:
# TODO: bug with rewards

def old_trajectory(env, agent1, agent2):
    env.reset()

    states = []
    actions = []
    rewards = []

    counter = 0
    for agent in env.agent_iter():
        
        observation, reward, termination, truncation, info = env.last()
        if termination or truncation:
            break
        state = observation['observation']

        if agent == "player_1":
            action = agent1.pick_action(env)
        else:
            action = agent2.pick_action(env)
        
        states.append(state)
        actions.append(action)
        if counter >= 2:
            rewards.append(reward)

        # rewards
        if counter >= 2:
            if agent == "player_1":
                rewards
        
        env.step(action)
        counter += 1
    rewards.append(env.rewards[env.agent_selection])
    env.agent_selection = env._agent_selector.next()
    rewards.append(env.rewards[env.agent_selection])

    return states, actions, rewards

# def split_trajectory(trajectory):
#     # states, actions, rewards = trajectory
#     # return {"player_1": {'states': states[0::2], 'actions': actions[0::2], 'rewards': rewards}}

In [6]:
def compute_trajectory(env, agent1_policy, agent2_policy):
    """
    Collects a trajectory for two agents using env.last() and env.agent_iter().
    """
    env.reset()

    trajectory = {
        "player_1": {"observations": [], "actions": [], "rewards": []},
        "player_2": {"observations": [], "actions": [], "rewards": []},
    }
    turn = 0
    for agent in env.agent_iter():
        obs, reward, termination, truncation, info = env.last()  # get last step info

        if termination or truncation:
            action = None  # agent is done, no action to take
        else:
            # choose action according to agent
            if agent == "player_1":
                action = agent1_policy.pick_action(env)
            else:
                action = agent2_policy.pick_action(env)

        # Record observation, action, reward
        if not (termination or truncation):
            trajectory[agent]["observations"].append(obs['observation'])
            trajectory[agent]["actions"].append(action)
        if turn >= 2:
            trajectory[agent]["rewards"].append(reward)

        env.step(action)  # take the action (None if done)
        turn += 1

    return trajectory

In [7]:
a1 = ManualAgent("player_1")
a2 = RandomAgent("player_2")

In [8]:
env.metadata['render_fps'] = 5

In [9]:
a, b = '0 0'.split(' ')

In [10]:
int(a)

0

In [ ]:
r = (env, a1, a2)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
0 0
[[0 0 0]
 [0 0 0]
 [0 0 0]]
4 4
[[0 0 0]
 [0 0 0]
 [0 0 0]]
8 8
[[0 0 0]
 [0 0 0]
 [0 0 0]]
3 3
[[0 0 0]
 [0 0 0]
 [0 0 0]]
4 7
[[0 0 0]
 [0 0 0]
 [0 0 0]]
4 1
[[0 0 0]
 [0 1 0]
 [0 0 0]]


ValueError: not enough values to unpack (expected 2, got 1)

# REINFOCE

In [ ]:
a = NeuralAgent("agent")

In [ ]:
def reinforce(env, agent1, agent2, num_episodes, gamma):
    for episode in range(num_episodes):
        trajectory = compute_trajectory(env, agent1, agent2)


# Stats

In [29]:
result = np.zeros(3)

In [26]:
env = ultimatetictactoe.env(render_mode="rgb_array")
env.reset(42)

In [ ]:
a1 = RandomAgent("player_1")
a2 = RandomAgent("player_2")   

In [50]:
n = 100000
result = np.zeros(3)
for _ in range(n):
    r = compute_trajectory(env, a1, a2)
    reward_1 = r['player_1']['rewards'][-1]
    if reward_1 == 1:
        result[0] += 1
    elif reward_1 == -1:
        result[1] += 1
    elif reward_1 == 0:
        result[2] += 1

In [51]:
result * 100 / n

array([41.326, 36.656, 22.018])